// import { ExecResult } from "~/types/Event"

// export function ErrCatch(target: Function): ExecResult
// {
//     try{
//         target()
//     }
//     catch (err) {
//         if(err instanceof Error)
//         {
//             console.log(err.message)
//             return {
//                 succeed: false,
//                 message: err.message
//             }
//         }
//         return {
//             succeed: false,
//             message: "未知原因"
//         }
//     }
// }
